tfadeyi/auth0-simple-exporter

.github/workflows/release.yml
This will allow the deployment of a swagger ui on github pages at every new tag release.
No testing.
No Ref
=> Add github action for swagger deployment

.github/workflows/release.yml
Fixes the issues present in the release workflow in the pipeline.
No test.
No ref.
=> Fix release workflow ci issue

.github/workflows/release.yml
The fixes to the swagger ui ci/cd generation.
No testing.
No ref.
=> Fixes to swagger site

deploy/charts/auth0-exporter/Chart.yaml
=> Update Helm chart version

.github/workflows/release.yml, README.md
=> Fix helm release CI step

.github/workflows/release.yml
=> Fix helm chart path

.github/workflows/release.yml, README.md, deploy/charts/auth0-exporter/Chart.yaml, deploy/charts/auth0-exporter/README.md, deploy/charts/auth0-exporter/README.md.gotmpl, pkg/docs/docs.go, pkg/docs/swagger.json, pkg/docs/swagger.yaml, pkg/exporter/server.go
=> Clean documentation

README.md, deploy/charts/auth0-exporter/README.md, deploy/charts/auth0-exporter/README.md.gotmpl
=> Fix helm installation command

README.md
=> Add goreport card

.github/workflows/release.yml, Makefile, default.nix, deploy/charts/auth0-exporter/Chart.yaml, deploy/charts/auth0-exporter/README.md, deploy/charts/auth0-exporter/values.yaml, gomod2nix.toml, pkg/docs/docs.go, pkg/docs/swagger.json, pkg/docs/swagger.yaml, pkg/exporter/server.go
* Updated helm to v0.1.1
* Updated openapi spec to v0.1.1
* Updated nix flake to v0.1.1
* Removed unused Makefile target
=> New release update

.github/workflows/ci.yml, .golangci.yml, pkg/client/client.go, pkg/exporter/exporter.go, pkg/exporter/exporter_test.go, pkg/exporter/metrics/metrics.go
* Fix lint and formatting issues in latest changes.
* Update setup-go to go 1.20
=> Fix Lint and Formatting errors

default.nix, deploy/charts/auth0-exporter/Chart.yaml, pkg/docs/docs.go, pkg/docs/swagger.json, pkg/docs/swagger.yaml, pkg/exporter/server.go
Updated references  for v0.2.0 release
=> Prepare release v0.2.0

docs/metrics.md
Updates documentation with new metric after latest release
No testing required
=> update documentation for tenant_total_monthly_active_users

README.md
* Add documentation octopus deploy 
* #100
=> Add docs on octopus deploy

default.nix, deploy/charts/auth0-exporter/Chart.yaml
* update the helm chart to point to the latest release
* update Nix flake to point to the latest release
=> Update the helm chart and nix flake with latest release

README.md
* Added list of grants needed to run the tool
=> Add current list of grants needed to run the exporter

.github/workflows/chart-testing.yaml, .github/workflows/setup_environment/action.yaml, chart-testing.yaml, deploy/charts/auth0-exporter/templates/deployment.yaml
- Fixes duplicate `ports` entries in `deployment.yaml` of the helm chart
- Adds `chart-testing` workflow
=> fix: duplicate ports entry in chart

.github/workflows/chart-testing.yaml
* Fix the small issue on the helm test github action workflow
=> fix(helmtest): minor fix to helm test

.github/workflows/ci.yml
=> fix(ci): run test on push to master

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, flake.lock, go.mod, go.sum, gomod2nix.toml
* Updates the tool to go 1.2.1
* Test suite is passing
=> chore(go): Update to go 1.21

.goreleaser.yaml
* Make goreleaser sign all artifacts.
=> build(goreleaser): update goreleaser config

pkg/exporter/exporter.go
* Slight improvement to the logging during the logs collection
=> feat(logging): add better logs during export

pkg/client/logs/logs.go, pkg/client/logs/logs_test.go
Updates how the auth0 log client finds the initial log checkpoint used for the checkpoint pagination.
The checkpoint is now found by querying the Auth0 API to return only the last log from the day prior to the `from` date this is then used as the initial checkpoint from where all the other logs will be fetched.
* Update the logs client, to fetch the checkpoint log in a more incremental way.
* Manually run the exporter:
```shell
./exporter  export --tls.disabled --log.level debug --auth0.from 2023-11-18
```
=> fix(timeout): update auth0 log client

.github/workflows/chart-testing.yaml, deploy/charts/auth0-exporter/Chart.yaml, deploy/charts/auth0-exporter/README.md, deploy/charts/auth0-exporter/templates/deployment.yaml, deploy/charts/auth0-exporter/values.yaml
* Brings back the `tls.disabled` value to the chart, to avoid any breaking changes.
* Updates the `exporter.metrics.users.disabled` to `enabled`.
=> fix(chart): Revert previous changes to the helm chart

README.md, deploy/charts/auth0-exporter/Chart.yaml, deploy/charts/auth0-exporter/README.md, deploy/charts/auth0-exporter/README.md.gotmpl, deploy/charts/auth0-exporter/values.yaml, gomod2nix.toml
* Fix READMEs
* Remove image default value in Values.yaml of the helm chart
=> fix(installation): fix helm installation docs

.github/workflows/ci.yml
* Update the go version in the CI/CD pipeline
=> chore: update go version in CI

README.md
=> add documentation for using the exporter in a docker environment
